# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20170215_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_products',
        ),
        migrations.AddField(
            model_name='store',
            name='store_products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogue.StoreProduct'),
        ),
        migrations.RemoveField(
            model_name='storeproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='product',
            field=models.ManyToManyField(to='catalogue.Product'),
        ),
    ]
