# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20170215_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.StoreProduct'),
        ),
    ]
