# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0012_auto_20170215_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_admins',
        ),
        migrations.AddField(
            model_name='store',
            name='store_admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_products',
        ),
        migrations.AddField(
            model_name='store',
            name='store_products',
            field=models.ManyToManyField(to='catalogue.Product'),
        ),
        migrations.DeleteModel(
            name='StoreProduct',
        ),
    ]
