# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0016_auto_20170215_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_admins',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
